import Foundation


//Boa prática colocar nome da várivael tipo lista ser de mesmo nome da classe no plural (se coloar List não coloca no plural
public let regionalSlangList: [RegionalSlang] = [
    RegionalSlang(name: "[It] died glueing [something]",
                  namePtBr: "in portugese: Morreu de colar!",
                  meaning: "Meaning: something that worked out; something that met expectations.",
                  photo: "diedGlueing.png",
                  audio: "morreuDeColar.wav",
                  card: "cardDiedGlueing.png"),
    RegionalSlang(name: "Nail box",
                  namePtBr: "in portugese: Caixa prego.",
                  meaning: "Meaning: a place that is far away.",
                  photo: "nailBox",
                  audio: "caixaPrego.wav",
                  card: "cardNailBox.png"),
    RegionalSlang(name: "Take your snack",
                  namePtBr: "in portugese: Pega a tua merenda!",
                  meaning: "Meaning: it serves you right.",
                  photo: "takeYourSnack.png",
                  audio: "pegaTuaMerenda.wav",
                  card: "cardTakeYourSnack.png"),
    RegionalSlang(name: "Whip on the bucket",
                  namePtBr: "in portugese: Chibata no balde!",
                  meaning: "Meaning: something or someone that is very good, very cool.",
                  photo: "whipOnTheBucket.png",
                  audio: "chibataNoBalde.wav",
                  card: "cardWhipOnTheBucket.png"),
    RegionalSlang(name: "Drilled",
                  namePtBr: "in portugese: Brocado.",
                  meaning: "Meaning: very hungry; starving.",
                  photo: "drilled.png",
                  audio: "brocado.wav",
                  card: "cardDrilled.png"),
    RegionalSlang(name: "Mare`s father",
                  namePtBr: "in portugese: Pai d`égua!",
                  meaning: "Meaning: something or someone that  is very good, very cool.",
                  photo: "maresFather.png",
                  audio: "paiDégua.wav",
                  card: "cardMaresFather.png"),
    RegionalSlang(name: "Cutting",
                  namePtBr: "in portugese: Cortando.",
                  meaning: "Meaning: speak badly of someone; bad-mouth someone.",
                  photo: "cutting.png",
                  audio: "cortando.wav",
                  card: "cardCutting.png"),
    RegionalSlang(name: "Just floating",
                  namePtBr: "in portugese: Só de bubuia.",
                  meaning: "Meaning: when someone is resting; not doing anything.",
                  photo: "justFloating.png",
                  audio: "soDeBubuia.wav",
                  card: "cardJustFloating.png"),
]


